## List 

<img src="images/list01.jpeg"/>

<img src="images/list02.jpeg"/>
<img src="images/list03.jpeg"/>

In [52]:
list1 = [2,3,4,5,6,7,8,9]
list2 = [1,3,4,5,6,6,7]
print(list1)
print(list2)

[2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 4, 5, 6, 6, 7]


In [11]:
print("list1 berisikan:", len(list2))
print(list1 + list2)
print(list1*3)
print("dalam list1 apakah ada angka 3:", 3 in list1)
print("dalam list1 apakah ada angka 13:", 13 in list1)


list1 berisikan: 7
[2, 3, 4, 5, 6, 7, 8, 9, 1, 3, 4, 5, 6, 6, 7]
[2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9]
dalam list1 apakah ada angka 3: True
dalam list1 apakah ada angka 13: False


In [12]:
for i in list1: print(i)

2
3
4
5
6
7
8
9


In [14]:
for i in range(len(list1)): print(i)

0
1
2
3
4
5
6
7


In [53]:
list1

[2, 3, 4, 5, 6, 7, 8, 9]

In [56]:
print(list1[::-2])

[9, 7, 5, 3]


In [21]:
print(list1[3]) #5
print(list1[1:5]) # x>=1 and x<5
print(list1[-1])
print(list1[-2])

print(list1[:4])
print(list1[4:])


5
[3, 4, 5, 6]
9
8
[2, 3, 4, 5]
[6, 7, 8, 9]


In [23]:
print(list1[:-3])
print(list1[-3:])

[2, 3, 4, 5, 6]
[7, 8, 9]


## Tuple 

<img src="images/tuple01.jpeg"/>

<img src="images/tuple02.jpeg"/>

## Array 

In [57]:
import numpy as np


In [25]:
list1 = [2,4,3,5,4,7,8,-8]
array1 = np.array(list1).astype(float)

print(list1)
print(array1)

[2, 4, 3, 5, 4, 7, 8, -8]
[ 2.  4.  3.  5.  4.  7.  8. -8.]


In [26]:
print(list1*2)
print(array1*2)

[2, 4, 3, 5, 4, 7, 8, -8, 2, 4, 3, 5, 4, 7, 8, -8]
[  4.   8.   6.  10.   8.  14.  16. -16.]


In [28]:
# Matriks 2 dimensi
list_2D = [[2, 3, 4, -5, 9], [5, 6, 7, -9, 5], [7, -7, 8, 1, 2], [4, -4, 5, 6, 7],[8, 9, 9, -2, -3]]

In [29]:
print(list_2D)

[[2, 3, 4, -5, 9], [5, 6, 7, -9, 5], [7, -7, 8, 1, 2], [4, -4, 5, 6, 7], [8, 9, 9, -2, -3]]


In [59]:
matriks = np.array(list_2D).astype(float)
print(matriks)

[[ 2.  3.  4. -5.  9.]
 [ 5.  6.  7. -9.  5.]
 [ 7. -7.  8.  1.  2.]
 [ 4. -4.  5.  6.  7.]
 [ 8.  9.  9. -2. -3.]]


In [61]:
print(matriks[2])
print(matriks[-1])

[ 7. -7.  8.  1.  2.]
[ 8.  9.  9. -2. -3.]


In [72]:
print(matriks[:,:])

[[ 2.  3.  4. -5.  9.]
 [ 5.  6.  7. -9.  5.]
 [ 7. -7.  8.  1.  2.]
 [ 4. -4.  5.  6.  7.]
 [ 8.  9.  9. -2. -3.]]


In [92]:
x = np.array([0, 0, -1, -2]).astype(float)
y = x/-1

In [91]:
print(y*2)
print(y[0]/)

[-0. -0.  2.  4.]
0.0


In [64]:
print(matriks[:,1])

[ 3.  6. -7. -4.  9.]


In [65]:
print(matriks[1,3])

-9.0


In [66]:
print(matriks[2:4,2:4])

[[8. 1.]
 [5. 6.]]


In [ ]:
r11 = m11/max(C1)
r21 = m21/max(C1)

In [67]:
C1 = matriks[:,0]
print(C1)

[2. 5. 7. 4. 8.]


In [86]:
r11 = matriks[0,0]/np.max(C1)
r21 = matriks[1,0]/np.max(C1)
print('r11:',round(r11,2))
print('r21:',round(r21,2))

r11: 0.25
r21: 0.62
