In [16]:
data = [[2,3,4,6,4],[4,5,6,7,5],[5,5,7,2,6],[3,4,5,1,7],[4,8,2,3,3],[4,4,5,8,5],[8,8,7,1,4]]

bobot = [4,2,2,4,3]

# atribut:
#     benefit = 1
#     cost = 0
    
attribute = [0,1,1,0,1]




In [15]:
import numpy as np
data = np.array(data).astype(float)

print(data)
print(bobot)
print(attribute)

[[2. 3. 4. 6. 4.]
 [4. 5. 6. 7. 5.]
 [5. 5. 7. 2. 6.]
 [3. 4. 5. 1. 7.]
 [4. 8. 2. 3. 3.]
 [4. 4. 5. 8. 5.]
 [8. 8. 7. 1. 4.]]
[4, 2, 2, 4, 3]
[0, 1, 1, 0, 1]


In [19]:
#bobot
# bobot = [x/np.sum(bobot) for x in bobot]
bobot_=[]
for x in bobot:
    x_=x/np.sum(bobot)
    bobot_.append(x_)
bobot_

[0.26666666666666666,
 0.13333333333333333,
 0.13333333333333333,
 0.26666666666666666,
 0.2]

In [21]:
bobot_ = [round(x,2) for x in bobot_]
print(bobot_)
bobot = bobot_
# print(np.sum(bobot_))

[0.27, 0.13, 0.13, 0.27, 0.2]


In [5]:
x, y = data.shape
print(x,y)

7 5


In [6]:
if (y != len(bobot)):
    print('jumlah kriteria dan bobot tidak sama!!!')
elif(y!= len(attribute)):
    print('jumlah atribute dan kriteria tidak sama!!!')
else:
    print('OK, data bisa diproses!!!')

OK, data bisa diproses!!!


In [7]:
def normalisasi(data):
    x, y = data.shape
    data_normal=[]
    for i in range(x):
        data_=[]
        for j in range(y):

            if attribute[j] == 0:
                r = round(np.min(data[:,j])/data[i,j],2)
    #             print(data[i,j], "min:", np.min(data[:,j]))

            else:
                r = round(data[i,j]/np.max(data[:,j]),2)
    #             print(data[i,j],"max:", np.max(data[:,j]))

            data_.append(r)
    #     print(data_)
        data_normal.append(data_)
    data_normal = np.array(data_normal).astype(float)
#     print(data_normal)
    return data_normal

In [8]:
R = normalisasi(data)

In [9]:
print(R)

[[1.   0.38 0.57 0.17 0.57]
 [0.5  0.62 0.86 0.14 0.71]
 [0.4  0.62 1.   0.5  0.86]
 [0.67 0.5  0.71 1.   1.  ]
 [0.5  1.   0.29 0.33 0.43]
 [0.5  0.5  0.71 0.12 0.71]
 [0.25 1.   1.   1.   0.57]]


In [10]:
def final(R):
    x, y = R.shape
    hasil=[]
    for i in range(x):
        z_=0
        for j in range(y):
            z = R[i,j]*bobot[j]
            z_ += z
        hasil.append(round(z_,2))
    return hasil

hasil = final(R)
print(hasil)

[0.55, 0.51, 0.63, 0.81, 0.48, 0.47, 0.71]


In [11]:
x=1
winner = np.max(hasil)
for i in hasil:
    print('A>',x,':', i,end='')
    if i >= winner:
        print(' ==> winner')
    else:
        print("")
    x+=1

A> 1 : 0.55
A> 2 : 0.51
A> 3 : 0.63
A> 4 : 0.81 ==> winner
A> 5 : 0.48
A> 6 : 0.47
A> 7 : 0.71
