In [36]:
data = [[2,3,4,6,4],
        [4,5,6,7,5],
        [5,5,7,2,6],
        [3,4,5,1,7],
        [4,8,2,3,3],
        [4,4,5,8,5],
        [8,8,7,1,4],
       [2,3,9,9,1]]

bobot = [4,2,2,4,3]
attribute = [0,1,1,0,1]

# atribut:
#     benefit = 1
#     cost = 0
    


In [37]:
import numpy as np
#data list>array
data = np.array(data).astype(float)
print(data)

[[2. 3. 4. 6. 4.]
 [4. 5. 6. 7. 5.]
 [5. 5. 7. 2. 6.]
 [3. 4. 5. 1. 7.]
 [4. 8. 2. 3. 3.]
 [4. 4. 5. 8. 5.]
 [8. 8. 7. 1. 4.]
 [2. 3. 9. 9. 1.]]


In [38]:
#menyesuaikan bobot
w = [round(x/np.sum(bobot),2) for x in bobot]
# w = []
# for x in bobot:
#     w_ = round(x/np.sum(bobot),2)
#     w.append(w_)
print(w)

[0.27, 0.13, 0.13, 0.27, 0.2]


In [39]:
x, y = data.shape
print(x)
print(y)

8
5


In [40]:
# print(attribute)
def normalisasi(data):
    x, y = data.shape
    R = []
    for i in range(x):
        r = []
        for j in range(y):
            if attribute[j] == 0:
    #             print(data[i,j])
    #             print('min:', np.min(data[:,j]))
                r_ = round(np.min(data[:,j])/data[i,j],2)

            else:
    #             print(data[i,j])
    #             print('max:', np.max(data[:,j]))
                r_ = round(data[i,j]/np.max(data[:,j]),2)

            r.append(r_)
        R.append(r)
    R = np.array(R).astype(float)
    return R
R = normalisasi(data)
print(R)


[[1.   0.38 0.44 0.17 0.57]
 [0.5  0.62 0.67 0.14 0.71]
 [0.4  0.62 0.78 0.5  0.86]
 [0.67 0.5  0.56 1.   1.  ]
 [0.5  1.   0.22 0.33 0.43]
 [0.5  0.5  0.56 0.12 0.71]
 [0.25 1.   0.78 1.   0.57]
 [1.   0.38 1.   0.11 0.14]]


In [44]:

def Final(R):
    x, y = R.shape
    Hasil = []
    for i in range(x):
        a = 0
        for j in range(y):
            a += R[i,j]*w[j]
        Hasil.append(round(a,2))
    return Hasil

Hasil = Final(R)
print(Hasil)        
        

[0.54, 0.48, 0.6, 0.79, 0.47, 0.45, 0.68, 0.51]


In [42]:
v=1
winner = np.max(Hasil)
for i in Hasil:
    print('V-',v,':',i,end="")
    if(i>=winner):
        print('==> Winner')
    else:
        print('')
    v+=1

V- 1 : 0.54
V- 2 : 0.48
V- 3 : 0.6
V- 4 : 0.79==> Winner
V- 5 : 0.47
V- 6 : 0.45
V- 7 : 0.68
V- 8 : 0.51
